### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by energy11a** [AmyMialeeMods/no-enchant-cap#10]
[latest.log](https://github.com/AmyMialeeMods/no-enchant-cap/files/8008843/latest.log)

**Comment by AmyMialee** [comment]
The mod is incompatible with fair Enchanting at the moment. I am going to add my own fairer enchant cost to the Enchanting table eventually, at the moment it already has it for the anvil.

**Comment by energy11a** [comment]
Works, thanks.
