### ISSUE TITLE
Config File Not Created or Exists

### ISSUE THREAD

**Issue by Marcus101RR** [AmyMialeeMods/no-enchant-cap#12]
**Client/Server Version:** Forge 1.19 41.0.17
**Mod Version:** 1.18 (Jan 5, 2022)
**Standalone (No Other Mods):** Yes

I have ran both the server and client version of the game to see if this mod operates even though it is originally designed for 1.18. Since nothing significant changed in the enchantment variables it still works. The client refuses to load the mod entirely as it doesn't appear in the list, however, the server does load it and was able to enchant beyond the limit. The problem is config options are not available in documentation, or a template of the json file, nor does the actual plugin make a pre-existing config file on initialization like it should normally do.

Originally went on the Discord Server to see people have the same issue and the staff were very rude about it claiming it is a incompatibility issue or using too many mods. Maybe try it yourself to confirm? In any case, not working. If we can at least get a template and run it ourselves that is fine, that way we don't have to worry about the mod itself initializing the config.

EDIT: Here is the config for "FORGE" version:

Place in your _config folder_ and name it **"no-enchant-cap.toml"**. It will work, managed to merge with anvil a X enchantment.
```
removeAnvilXPLimit = true
allowAllEnchantmentCombinations = true
allowAnyEnchantOnAnyItem = true
removeAnvilLevelLimit = false
fairLevelCost = true
removeRepairCostIncrease = true
newAnvilLevelLimit = 30
```

**Comment by AmyMialee** [comment]
this is a fabric mod lol if that worked that's wild

**Comment by PseudoDistant** [comment]
Oh great, now I have to get Fabric mods running on Forge...

I've already started on two other compatibility layers, time for round three...
