### ISSUE TITLE
[Feature Request] Specify Max Level of Enchants In Config

### ISSUE THREAD

**Issue by mulfok** [AmyMialeeMods/no-enchant-cap#15]
To my knowledge right now (and sorry if it's actually _already_ in the mod and I'm just blind) the mod only has an option to `removeAnvilLevelLimit`, and you can specify the max level of enchant for everything(?) with `newAnvilLevelLimit`.

It would be nice though, to be able to specify the max level for each level that you want using the config file.

Perhaps something like:
```
# If first argument is just a number, then it acts same as "newAnvilLevelLimit"
# Otherwise default limits are kept bar for enchants mentioned after.
anvilLevelLimit: efficiency:8, unbreaking:8, protection:6
```

Hopefully it wouldn't be too complicated to add, but it would be a really nice addition to this mod!

**Comment by AmyMialee** [comment]
This would be too complicated for me to add for sure, but if someone was to pull request it I'd accept it.

**Comment by AmyMialee** [comment]
Sticking by that and closing the issue, anyone can feel free to pr it.

**Comment by FrozenDragon0** [comment]
Unfortunate this won't be added, would've been a nice feature to have now that the limitless mod is now completely non-existent for whatever reason.
