### ISSUE TITLE
fish

### ISSUE THREAD

**Issue by 54dsa** [AmyMialeeMods/no-enchant-cap#18]
Fishing is not good, as long as the enchantment exceeds level 5, you can't catch fish, whether it is bait or sea care

**Comment by 54dsa** [comment]
[noenchantcap-fabric-1.19.2-2.2.0.jar]Mod menus are not supported

**Comment by AmyMialee** [comment]
> [noenchantcap-fabric-1.19.2-2.2.0.jar]Mod menus are not supported

not supported?

**Comment by AmyMialee** [comment]
the mod has no config file for mod menu to edit if that's what you mean, it's all gamerules

**Comment by AmyMialee** [comment]
fish fixed in 2.2.1

**Comment by 54dsa** [comment]
Version 2.1.3 can open the module menu for configuration
![1669262737274](https://user-images.githubusercontent.com/116626829/203692590-d42253fe-7965-400e-b82f-83c9146c5e51.png)

**Comment by 54dsa** [comment]
However, it is not supported in version 2.2.1
![1669262975680](https://user-images.githubusercontent.com/116626829/203692704-5dcff24c-bbb6-44f2-8f3b-42542af2db9b.png)

**Comment by 54dsa** [comment]
Why do I use bait 3 doesn't add up, all enchantment books don
![1669263804517](https://user-images.githubusercontent.com/116626829/203693855-2874e518-bf7f-4107-8e88-c468126860d4.png)
't cumulative

**Comment by AmyMialee** [comment]
> However, it is not supported in version 2.2.1
> ![1669262975680](https://user-images.githubusercontent.com/116626829/203692704-5dcff24c-bbb6-44f2-8f3b-42542af2db9b.png)
> 

the Configs are removed from the mod, it uses game rules now.

**Comment by AmyMialee** [comment]
> Why do I use bait 3 doesn't add up, all enchantment books don
> ![1669263804517](https://user-images.githubusercontent.com/116626829/203693855-2874e518-bf7f-4107-8e88-c468126860d4.png)
> 't cumulative

you need the gamerule noenchantcap:uncapped_anvils to be true

**Comment by 54dsa** [comment]
I think it would be a little easier to use the mod menu

**Comment by 54dsa** [comment]
If you change the rules of the game, there will be many white players who will not use it

**Comment by 54dsa** [comment]
If you change it to the rules of the game, there will be many rookie players who will not use it, such as me

**Comment by AmyMialee** [comment]
Honestly the mod is very unbalanced, so I think players should have to choose to turn on the very unbalanced settings.
The only settings on at the start are the fair ones that are fine.

**Comment by 54dsa** [comment]
There are many players in China who like to play this type of mod

**Comment by 54dsa** [comment]
Can I continue to support the configuration of the module menu?

**Comment by 54dsa** [comment]
Can you continue to support the configuration of the mod menu?

**Comment by AmyMialee** [comment]
You just need to do the command /gamerule noenchantcap:uncapped_anvils true in chat with cheats on
