### ISSUE TITLE
1.19.2 Crash on startup.

### ISSUE THREAD

**Issue by Wubzzz1337** [AmyMialeeMods/no-enchant-cap#22]
Hey,

Can't figure out what mod causes the incompatibility maybe you can?

[latest.log](https://github.com/AmyMialeeMods/no-enchant-cap/files/10103010/latest.log)
[debug.log](https://github.com/AmyMialeeMods/no-enchant-cap/files/10103011/debug.log)

**Comment by AmyMialee** [comment]
It seems Apotheosis is having a lot of hits with this and other mods.

**Comment by Wubzzz1337** [comment]
Will you try to add compatibility? ❤️ 
It's quite a popular mod and I can't remove it from my modpack because it's actively used in it x)

**Comment by AmyMialee** [comment]
It's quite hard to tell where it's causing the issue, I'm not largely used to forge Modding.
You might not need this mod with apotheosis since it does a lot of the same things I think, or atleast it can in the config.

**Comment by AmyMialee** [comment]
Closing for now since compat probably isn't needed.
