### ISSUE TITLE
1.19.2 Crash on Start Up

### ISSUE THREAD

**Issue by Pengu-Hunter** [AmyMialeeMods/no-enchant-cap#23]
Forge 43.1.58
No Enchant Cap 2.2.2
Friends&Foes 1.6.1
I'm not sure which mod is causing it but if i try and launch with only these two the crash log says;
Exception in thread "main" java.lang.module.ResolutionException: Modules MixinExtras and noenchantcap export package com.llamalad7.mixinextras.utils to module forge.

Any help would be appreciated.

**Comment by AmyMialee** [comment]
need logs

**Comment by Pengu-Hunter** [comment]
[latest.log](https://github.com/AmyMialeeMods/no-enchant-cap/files/10137857/latest.log)

**Comment by krjencik** [comment]
1.19.3: cant create a new world
[latest.log](https://github.com/AmyMialeeMods/no-enchant-cap/files/10244318/latest.log)

**Comment by AmyMialee** [comment]
> 1.19.3: cant create a new world [latest.log](https://github.com/AmyMialeeMods/no-enchant-cap/files/10244318/latest.log)

could you open a new issue for this, as it's unrelated

**Comment by AmyMialee** [comment]
> [latest.log](https://github.com/AmyMialeeMods/no-enchant-cap/files/10137857/latest.log)

And honestly I'm not sure how this can be fixed, I'm not too familiar with forge so I'm not sure if this is a mistake on my end or some other mod's end.

**Comment by AmyMialee** [comment]
> 1.19.3: cant create a new world [latest.log](https://github.com/AmyMialeeMods/no-enchant-cap/files/10244318/latest.log)

fixed in 2.2.5

**Comment by Pengu-Hunter** [comment]
Thanks for the fix.
