### ISSUE TITLE
Compatibility with Enchanting Infuser

### ISSUE THREAD

**Issue by Wubzzz1337** [AmyMialeeMods/no-enchant-cap#24]
Here is the other mod: https://www.curseforge.com/minecraft/mc-mods/enchanting-infuser-forge
Right now if you change the gamerules to allow any enchantments on any Item etc, the Infuser does not follow the rule.
Maybe it needs to be adjusted with the other mod, I just thought maybe post it here first tho :)

**Comment by AmyMialee** [comment]
I think it would make sense for enchanting infuser to add this feature, since if I do it from this side it will require a lot of hooking into the mod, while for them they can add it without mixin.

**Comment by AmyMialee** [comment]
Yea from the looks of it this is more of a feature request for the other mod than anything to do with this mod.

**Comment by AmyMialee** [comment]
I always forget about close as not planned.
