### ISSUE TITLE
Game doesn't start with this mod

### ISSUE THREAD

**Issue by alessandriLuca** [AmyMialeeMods/no-enchant-cap#27]
Hi, attached you can find the log. Minecraft just crash during the loading of the game. Removing this mod let the game start. Thanks for your work!! Minecraft 1.19.2
[latest.log](https://github.com/AmyMialeeMods/no-enchant-cap/files/10250972/latest.log)

**Comment by AmyMialee** [comment]
Could you try and see which other mod is conflicting with this one? Just removing half the mods or so until you can launch with this installed.
Otherwise this probably won't be fixed as there's too many possible causes.

**Comment by alessandriLuca** [comment]
The mod is apotheosis.

**Comment by alessandriLuca** [comment]
hi, sorry to bother, did you have time to take a look?

**Comment by AmyMialee** [comment]
You don't need this mod with apotheosis, you can just use one or the other.

**Comment by alessandriLuca** [comment]
but from what i understand with apotheosis i cannot enchant anything with any enchant, or combine any enchantment, something that with your mod i should do, isn't it?
