### ISSUE TITLE
Server compatability

### ISSUE THREAD

**Issue by MrXodus** [AmyMialeeMods/no-enchant-cap#29]
Does this mod work on servers, if so how do I make it work, i have tried changing the gamerules but it still doesnt work

**Comment by AmyMialee** [comment]
which parts specifically?

**Comment by MrXodus** [comment]
All of it. It says that the game rule has changed, but when I go to actually do it, it doesn't work

**Comment by AmyMialee** [comment]
I need more details, the mod definitely works on servers it has been used in events with large numbers of players without any issue.

**Comment by MrXodus** [comment]
That is all the details I have, I changed the gamerule on the server, when I tried to use the features they did not work, Ive used them on single player and did the same method

**Comment by MrXodus** [comment]
And they worked just fine

**Comment by MrXodus** [comment]
I have a server through bisect hosting

**Comment by AmyMialee** [comment]
I need more details or I can't do anything.

**Comment by MrXodus** [comment]
I can give you the ip to my server and you can test it out for yourself

**Comment by MrXodus** [comment]
204.152.220.169:25565

**Comment by MrXodus** [comment]
https://www.youtube.com/watch?v=fkUV9SZs22s

**Comment by MrXodus** [comment]
Any updates?

**Comment by AmyMialee** [comment]
i'm not sure, there's too many mods for me to able to pinpoint anything
