### ISSUE TITLE
Enchantment cost support

### ISSUE THREAD

**Issue by alfiejfs** [AmyMialeeMods/no-enchant-cap#3]
Some configuration options to reduce the enchanting cost of an item would be useful, as it can get very pricey with such high numbers

**Comment by AmyMialee** [comment]
Was this repair cost? Sorry I don't remember.
If you mention what it is I will probably add it in an update.

**Comment by chimericdream** [comment]
If this is what I think, I'd like to request it as well. Essentially, I'd like to be able to scale the higher level enchants better. As it stands, you can get to 500-1000+ levels per enchant pretty quickly.

**Comment by AmyMialee** [comment]
Too vague, can open a new issue with a clearer suggestion.

**Comment by AmyMialee** [comment]
Might actually already be in with the static repair costs gamerule, which just makes stuff not get more expensive.
