### ISSUE TITLE
Can't launch game with the Friends & Foes mod

### ISSUE THREAD

**Issue by Fluished** [AmyMialeeMods/no-enchant-cap#33]
I tried turning on mods 1 by 1 from top to bottom and,

This log contains all the mods I turned on before I reached Friends & Foes mod:

[latest.log](https://github.com/AmyMialeeMods/no-enchant-cap/files/10368552/latest.log)

2nd log with only Friends&Foes and this mod:

[latest.log](https://github.com/AmyMialeeMods/no-enchant-cap/files/10368571/latest.log)

I can't seem to launch the game with both mods turned on, launcher gives exit code 1.

**Comment by AmyMialee** [comment]
fixed 2.2.6
