### ISSUE TITLE
Feather Falling gives you additional hp fabric 1.19.2

### ISSUE THREAD

**Issue by amer776** [AmyMialeeMods/no-enchant-cap#34]
I know this issue is one you have solved in version 1.19.3 and closed it but can you make the same fix but for version 1.19.2 fabric, or make the 2.2.6 1.19.3 release work with 1.19.2 fabric

**Comment by amer776** [comment]
Hey are you going to make the change for 1.19.2?

**Comment by AmyMialee** [comment]
I'll accept any PR doing it but I don't think I'm going to do it myself. This mod is really low priority for me.
