### ISSUE TITLE
No config file for 1.19.2 mod version 2.2.4

### ISSUE THREAD

**Issue by bigbc8** [AmyMialeeMods/no-enchant-cap#39]
![image](https://user-images.githubusercontent.com/71859614/219526860-caf6e8bd-5f31-4083-b779-497f86af3a9e.png)
![image](https://user-images.githubusercontent.com/71859614/219526936-d02871ad-ea56-4860-a59f-e57961b12669.png)

**Comment by AmyMialee** [comment]
gamerules
and this is the nth duplicate

**Comment by bigbc8** [comment]
so i cant change it without having cheats enabled, correct?

**Comment by AmyMialee** [comment]
yes or on world creation

this mod is literally a cheat idk what you expect
