### ISSUE TITLE
High level protections can cause to give absorption hearts upon receiving damage

### ISSUE THREAD

**Issue by akaari-dv** [AmyMialeeMods/no-enchant-cap#40]
Hi,

I have used this mod on my RPG private server. I have noticed that once people got Feather Falling 5 on their diamond boots, they would start gaining absorption hearts upon receiving fall damage. I have also a custom mob on it that has Projectile Protection 10 on Netherite Chestplate and Helmet, and if it was shot with a power bow of any level it would also gain absorption hearts. This bug does not happen anymore when I remove no enchant cap and fall damage + mob damage is properly received. 

Version: Forge 43.2.4 MC 1.19.2 
Modversion: noenchantcap-forge-1.19.2-2.2.4
![image](https://user-images.githubusercontent.com/74096536/221332904-25d823ca-489a-448e-8791-1d2b5cacf755.png)

**Comment by AmyMialee** [comment]
fixed on latest
