### ISSUE TITLE
Anvil level combining still limited

### ISSUE THREAD

**Issue by bubbaryebread** [AmyMialeeMods/no-enchant-cap#41]
Hi! I've been using your mod, and have been really enjoying it so far, however I'm not able to get higher level enchantments. In the images there's an example of exceeding the enchanting limit by combining items on an anvil, however that's not working for me, and I'm not sure why. Is that something that needs to be fixed, or can that be changed somewhere? I've looked for a config file, but I don't see one in my configs folder. Thanks in advance!

**Comment by AmyMialee** [comment]
like I said to the dozens of other people, it's a gamerule

**Comment by bubbaryebread** [comment]
Gotcha. Sorry, didn’t think to check in other closed issues!
