### ISSUE TITLE
[Feature Request] Disable enchantment combination but allow to use books/tools with a higher enchant level

### ISSUE THREAD

**Issue by elhertz** [AmyMialeeMods/no-enchant-cap#6]
I made chest loot tables with enchantments like power 6, sharpness 8, etc. and wanted to be able to use them.
This mod solved the issue but now I've noticed that my loot chests make no sense anymore, because you can combine books or tools the same and get the high level enchantment without finding chests.

I wanted to make so you can't combine books/tools with enchantments but allowing to use these high level books found in dungeons. is there a way you can implement that?

**Comment by AmyMialee** [comment]
Yea funnily enough this is going to be the default setting in 1.18.1's release.

**Comment by elhertz** [comment]
That's amazing, thanks!

**Comment by AmyMialee** [comment]
Done in the new release.

**Comment by elhertz** [comment]
Hey!
I wasn't running my server when you implemented my suggestion so I didn't try it.
Now that I'm making another server I decided to try it but couldn't get it to work with the default settings.
It lets me enchant a sword with sharpness 6 in creative mode but when I try the same in survival it converts the output enchantment to sharpness 5. So I tried setting "removeAnvilLevelLimit" to true and now it works but I've noticed that now i cant combine any books infinitely (remember that I wanted my players to find these sharpness 6 books in treasure chests, not by combining sharpness 5 books).
Please let me know if my explanation sounds confusing. I hope it's possible to fix it, thanks.
