### ISSUE TITLE
Enchanted books above newAnvilLevelLimit are reverted to whatever it is set to

### ISSUE THREAD

**Issue by AxiosXx** [AmyMialeeMods/no-enchant-cap#9]
Enchanted books above the newAnvilLevelLimit value cannot be applied and will be reverted to whatever it is set to.

![image](https://user-images.githubusercontent.com/98239426/150658560-76bafadb-40e2-4fa0-98f5-4934ac5c7fab.png)

**Comment by AmyMialee** [comment]
What is the modlist? also what did the sword have at the start?

**Comment by AxiosXx** [comment]
The issue is an extension of the same vanilla mechanic: for example, trying to apply thorns 5 to a chestplate via an anvil will revert it to thorns 3. Before I knew this I tried removing all enchantment-related mods.

The diamond sword is unenchanted.
Here's the modlist taken from logs because I'm lazy:

- allarrowsinfinityfix 1.0.0
- amplified_nether 1.0.1
- antighost 1.18-fabric0.43.1-1.1.4
- anvilrestoration-fabric 1.1
- appleskin mc1.18-2.2.0
- architectury 3.4.9
- axolotlitemfix 1.1.3
- balm-fabric 2.4.1+0
- bcc fabric-1.0.4
- bclib 1.2.5
- bedspreads 1.5.0-1.18
- betterend 1.0.1
- betterf3 1.2.2
- betterfpsdist 1.18-1.5
- betterimpaling 2.0.4
- betterleads 1.0.1+1.18.1
- bettersafebed 1.18-fabric-a
- betterspawnercontrol-fabric 1.5
- betterthirdperson 1.6.0
- bettertridentreturn 1.18.1-1.0.2
- blockus 2.3.4+1.18.1
- bottledair-fabric 1.0
- bowinfinityfix rv11
- brb 1.5.6
- cardinal-components-base 4.0.1 via polymorph
- cardinal-components-block 4.0.1 via polymorph
- cardinal-components-entity 4.0.1 via polymorph
- cardinal-components-item 4.0.1 via polymorph
- cavetweaks 1.0
- cherishedworlds 2.0.1-1.18
- chisel 1.4.4
- chiselsandbits 1.2.77
- chunky 1.2.164
- cloth-basic-math 0.6.0 via cloth-config
- cloth-config 6.1.48
- collective-fabric 3.14
- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
- comforts 1.0.0-1.18
- conduitspreventdrowned-fabric 1.5
- continuity 1.0.3+1.18
- controlling 9.0.11
- crowdin-translate 1.4+1.18 via antighost
- customizableelytra 1.5.3-1.18
- customstars 0.7+1.18
- cyclepaintings-fabric 2.1
- decorative_blocks 2.0.4
- decorative_winter 2.0.1
- dismountentity-fabric 1.5
- doubledoors-fabric 3.1
- dynamicfps 2.1.0
- enchdesc 9.0.11
- expanded_armor_enchanting 1.0.2
- expanded_axe_enchanting 1.0.3
- expanded_trident_enchanting 1.0.3
- experiencebugfix 18
- extendedbonemeal-fabric 1.4
- fabric 0.46.1+1.18
- fabric-api-base 0.4.1+b4f4f6cd65 via fabric
- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
- fabric-blockrenderlayer-v1 1.1.9+3ac43d9565 via fabric
- fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
- fabric-containers-v0 0.1.18+d154e2c665 via fabric
- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
- fabric-dimensions-v1 2.1.9+a1d9bbf565 via fabric
- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
- fabric-item-api-v1 1.3.0+691a79b565 via fabric
- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
- fabric-key-binding-api-v1 1.0.8+c8aba2f365 via fabric
- fabric-keybindings-v0 0.2.6+b4f4f6cd65 via fabric
- fabric-language-kotlin 1.7.1+kotlin.1.6.10
- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
- fabric-mining-levels-v0 0.1.8+b4f4f6cd65 via fabric
- fabric-models-v0 0.3.3+3ac43d9565 via fabric
- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
- fabric-object-builder-api-v1 1.11.1+3b82842e65 via fabric
- fabric-object-builders-v0 0.7.9+3ac43d9565 via fabric
- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
- fabric-registry-sync-v0 0.9.0+befed49e65 via fabric
- fabric-renderer-api-v1 0.4.10+b0b66fc365 via fabric
- fabric-renderer-indigo 0.4.13+b0b66fc365 via fabric
- fabric-renderer-registries-v1 3.2.7+b4f4f6cd65 via fabric
- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
- fabric-rendering-v0 1.1.9+b4f4f6cd65 via fabric
- fabric-rendering-v1 1.10.3+6b21378a65 via fabric
- fabric-resource-conditions-api-v1 1.0.1+13eda06565 via fabric
- fabric-resource-loader-v0 0.4.11+3ac43d9514 via betterf3
- fabric-screen-api-v1 1.0.7+3ac43d9565 via fabric
- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
- fabric-structure-api-v1 2.1.0+0a73a6c265 via fabric
- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
- fabric-textures-v0 1.0.9+3ac43d9565 via fabric
- fabric-tool-attribute-api-v1 1.3.5+fb3b57b465 via fabric
- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
- fabricloader 0.12.12
- fastbench 1.18.1-3
- fastfurnace 1.18-4
- fastopenlinksandfolders 1.0.1
- feature_nbt_deadlock_be_gone 1.0.1+1.18.1
- ferritecore 4.0.0
- fiber 0.23.0-2 via collective-fabric
- fixedanvilrepaircost-fabric 1.6
- flytre-lib-base 1.3.0 via flytre_lib
- flytre-lib-compat 1.0.0 via flytre_lib
- flytre-lib-config 1.1.0 via flytre_lib
- flytre-lib-event 1.0.1 via flytre_lib
- flytre-lib-gui 1.0.0 via flytre_lib
- flytre-lib-storage 2.3.2 via flytre_lib
- flytre_lib 1.4.4
- forgottenrecipes 1.18.1-1.0.0
- fpsreducer 1.25-mc1.18
- ftblibrary 1801.3.5-build.109
- glassential 1.3.0
- glowingbanners 1.1.0
- grass_pass 1.1.0
- imm_ptl_core 1.2.3 via immersive_portals
- immersive_portals 1.2.3
- indium 1.0.2-alpha2+mc1.18.1
- inventorytotem-fabric 1.5
- iris 1.2.0-pre
- itemmodelfix 1.0.3+1.18
- java 17
- kleeslabs 11.0.0
- lambdynlights 2.1.0+1.17
- lazy-language-loader 0.2.6
- lazydfu 0.1.2
- libcd 3.0.3+1.16.3 via blockus
- lightoverlay 6.0.4
- lithium 0.7.7
- lootcrates 2.7.0-1.18.1
- lumiwool 1.2.2
- mavm 1.0.7a
- minecraft 1.18.1
- modmenu 3.0.1
- morebannerfeatures 1.1.3
- mousetweaks 2.22
- naturescompass 1.18.1-2.0.2-fabric
- netherportalfix 9.0.0
- no_null_processors 2.0.1+1.18.1
- noenchantcap 1.18.1-fabric-2.1.1
- nullscape 1.1
- omega-config 1.0.8 via repurposed_structures
- onsoulfire 1.18-1
- org_anarres_jcpp 1.4.14 via iris
- org_aperlambda_lambdajcommon 1.8.1 via spruceui
- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
- org_joml_joml 1.10.2 via sodium
- org_slf4j_slf4j-api 1.7.12 via iris
- oro_config 2.1.0 via cavetweaks
- patchouli 1.18.1-64-FABRIC
- polymorph 0.0.19-1.18.1
- pride 1.1.0+1.17 via lambdynlights
- q_misc_util 1.2.3 via immersive_portals
- reinfbarrel 1.0.6+1.18
- reinfchest 1.0.6+1.18
- reinfcore 1.1.3+1.18 via reinfbarrel
- reinfshulker 1.1.8+1.18
- repurposed_structures 3.3.3+1.18.1
- rib 1.1.0-1.18.1
- roughlyenoughitems 7.1.390
- scaffoldingdropsnearby-fabric 1.5
- seedfix 1.0.0 via amplified_nether
- shroomlight_slab 1
- skinlayers 1.3.1
- sodium 0.4.0-alpha6+build.14
- someforgepatchesported 1.0.2
- spruceui 3.3.0+1.17 via betterleads
- starlight 1.0.0+fabric.d0a3220
- surfacemushrooms-fabric 1.2
- terraform-wood-api-v1 2.0.2 via blockus
- terralith 2.0.12
- tooltipfix 1.0.4-1.18
- veinmining 0.0.11-1.18
- wooltweaks-fabric 1.4
- worldedit 7.2.8+6008-1246d61
- xaerominimap 22.1.0
- xaeroworldmap 1.20.0

**Comment by AmyMialee** [comment]
Not sure if present on the rewrite, closing for now.
